### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Galeanami** [scalda/Foolcraft_3#277] opened 2018-08-16 15:29 UTC
Hi. Today, for some reason, foolcraft decided to crash. I played yesterday without problem. https://pastebin.com/KgZeyW4J 

(first time doing this. going to try 1.5)

**Comment by Galeanami** [comment] 2018-08-16 15:45
Didn't work with 1.5. something about modified version. got no clue what that could be. i havn't done anything that i know of.  

this is the message:  The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)

**Comment by Kidokit** [comment] 2018-08-16 15:56
Pack Version: 1.4.5 and 1.5
[Yes] I am running FoolCraft via Curse/Twitch Launcher
[Yes] I can reproduce this issue consistently
[Yes, commented on this post about the issue] I have searched for this issue previously and it was either not previously reported or previously fixed and **I'm having the same problem**
[Yes] I am crashing and can provide my crash reports
[Yes] I have not altered the modpack

Issue Description;
   Launch the game in either v1.4.5 or v.1.5 and get this crash message;
     _The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)_
   
Additional information;
  I was on the game around 11:50pm EST yesterday and attempted to launch the game at 10:30am EST today and received the crash message.

Crash Report:
https://pastebin.com/mnut8JGd

**Comment by SubarcticPaper** [comment] 2018-08-16 15:57
I get the same error in 1.3.1 as well as all others above 1.3.1. I am not sure about the others below it. I have tried uninstalling and reinstalling however it still doesn't fix it.

**Comment by khodi7** [comment] 2018-08-16 15:57
Same here (it worked yesterday and I've got the same error message).
I'm on the 1.3.1 version.
I've reinstalled it but I've still got the same issue.

**Comment by artjumble** [comment] 2018-08-16 16:02
Interesting as this just happened to me also, again with the Extra Utilities 2 listed as the cause. Was there an update pushed out today? I was playing about 6 hours ago just fine, and now it won't launch.

**Comment by Kidokit** [comment] 2018-08-16 16:09
Just attempted to launch 1.5 Beta. Got the same crash message as before.

**Comment by scalda** [comment] 2018-08-16 16:14
Can you please fill out the template correctly also post a public crash report please otherwise I can't help

**Comment by Kidokit** [comment] 2018-08-16 16:14
Apologies, I was unaware there was a template

EDIT: I have edited my above post to use the error reporting template.

**Comment by Tommmy98** [comment] 2018-08-16 16:14
also having the same issue ....

**Comment by Galeanami** [comment] 2018-08-16 16:22
i have posted my crashreport up top. what is a template and where is it?

**Comment by scalda** [comment] 2018-08-16 16:25
Your crash report is set to private I can't see it

**Comment by Galeanami** [comment] 2018-08-16 16:27
ok sorry. first time using it
https://pastebin.com/KgZeyW4J

now?

**Comment by scalda** [comment] 2018-08-16 16:29
Is this loading the world or loading the pack? As the crash report is to do with the ExU manual that you have used

**Comment by Galeanami** [comment] 2018-08-16 16:32
The pack.

**Comment by simon44571** [comment] 2018-08-16 16:33
same issue here on all 3 of my pc's in my house.

**Comment by Galeanami** [comment] 2018-08-16 16:34
i havn't used that manual. strange.

**Comment by Kidokit** [comment] 2018-08-16 16:45
I have never used the manual

**Comment by ghost** [comment] 2018-08-16 16:49
Myself and a friend also have this issue

**Edit**: Though the error has changed after I reinstalled the pack, it's now The game crashed whilst stitching texture atlas instead of Caught exception from Extra Utilities 2 (extrautils2)

**Comment by scalda** [comment] 2018-08-16 17:22
If this is happening across versions then it's got to be the mod. It must
be trying to request something from somewhere

**Comment by SpongeRob093** [comment] 2018-08-16 17:25
I´m having the same problem. I played yesterday till 4am, today I tried to start the pack at 4pm but I keep crashing. I tried updating the pack from 1.4.5 to 1.5 and increased my java parameres to have 4GB available, but still no luck.

Crash report:
[crash-2018-08-16_19.20.19-client.txt](https://github.com/scalda/Foolcraft_3/files/2294611/crash-2018-08-16_19.20.19-client.txt)

**Comment by artjumble** [comment] 2018-08-16 17:41
It seems this may be caused by a launcher update
https://github.com/rwtema/Extra-Utilities-2-Source/issues/159
There are some workarounds listed there.
Edit to add: Switching to Jar launcher in Twitch fixed it for me.

**Comment by Maximinius** [comment] 2018-08-16 18:01
I'm having the exact same issue

https://pastebin.com/7gyigX5H

**Comment by SpongeRob093** [comment] 2018-08-16 18:17
Switching to the Jar launcher worked for me... 

To change it;
click on the 3 dashes on the top left of the twitch launcher.. file - settings - minecraft (left side) - select the launcher method to Jar.

P.S. You will need to reenter your email and password, and the stirling engine from enderio is missing.

**Comment by Mrbysco** [comment] 2018-08-16 18:21
This is not an issue with the modpack.
This is an issue from Mojang.

You need to go to the Minecraft tab and change from the Native Launcher to the Jar Launcher.

#BlameMojang

**Comment by nzminecraftDOTcom** [comment] 2018-08-16 18:45
Can confirm the workaround @SpongeRob093 posted works.
You may need to restart the launcher after re-entering your account information to make it recognise you're trying to load Foolcraft 3, not Vanilla 1.13

**Comment by Galeanami** [comment] 2018-08-16 19:04
maybe a stupid question. u mean closing and opening the minecraft launcher? =P

**Comment by nzminecraftDOTcom** [comment] 2018-08-16 19:16
Yeah, once you log back in (it happened to me so just sharing) it will then say "Play" and the version is 1.13. To resolve, I just close the launcher. Open twitch back up, start FC3 again.

**Comment by Kidokit** [comment] 2018-08-16 19:19
Tried the method @SpongeRob093 posted. It begins to launch the game then pops up an error message.
Java Virtual Machine Launcher:
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

EDIT: Will try closing out of Twitch Launcher completely then attempt again
EDIT EDIT: Did not work, going back to the default launcher and waiting on another fix

**Comment by nzminecraftDOTcom** [comment] 2018-08-16 19:41
Make sure you have java installed and the launcher is looking in the correct place for the Java files.

**Comment by Ad23** [comment] 2018-08-16 19:59
I'm having the same issue. I played fine last night but now there's no launching it. It gets halfway before crashing, stating problems loading either extra utils 2 or thermal foundation. At first i thought it might be due to having changed my memory settings, but setting them back to default didn't help. I (obviously) have no coding experience or understanding of the crashes but if any info i can provide would help, let me know how and what to include. thanks :)

**Comment by Kidokit** [comment] 2018-08-16 20:16
@nzminecraftDOTcom How do I make sure the launcher is looking for Java in the right place?
Sorry for the noob question

**Comment by nzminecraftDOTcom** [comment] 2018-08-16 22:10
In the profile settings when going to launch. Make sure the java path is valid (exists)

**Comment by Kidokit** [comment] 2018-08-17 02:20
@nzminecraftDOTcom I updated Java and double checked the java path. Everything is correct in the settings, I am now getting an Invalid Heap Size error, which I see scalda referenced another post to here, I am assuming for the profile and jar fix, which unfortunately, is not working for me

**Comment by scalda** [comment] 2018-08-20 10:03
ok this is all fixed whether it's been hacked in or fixed correctly so will now close

**Closed as completed** 2018-08-20 10:03 UTC
