### ISSUE TITLE
Game crashed opening a chance cube

### ISSUE THREAD

**Issue by dryzwell** [scalda/Foolcraft_3#245] opened 2018-07-26 17:27 UTC
## Issue Description
I opened a chance cube and for a half second I saw a tnt then it froze even before it could explode and then the game crashed. Now I cant even join the world before the game crashes again.

## Additional Information
Crashreport: https://pastebin.com/BL8apSPe

**Comment by Revvilo** [comment] 2018-08-01 11:37
Sorry, I meant to suggest this earlier, but from what I'm seeing in the crash report you might've had an inventory pet that is doing something to the TNT and breaking stuff.

How I'd attempt to fix it, since it's to do with an entity, is;
- **Make a backup of the world!** - I like to keep it as a separate "original broken" world, so you can go back to the start in case you *really* break things while trying to fix them.
- Navigate to the config folder for the modpack, find `forge.cfg` and open it.
- Then find the setting `removeErroringEntities` and set it to `true` and save the file.
- Start up (or restart) your game and log in to your world to see if it still crashes.
- If it lets you to load into the world alright again, you should change `removeErroringEntites` back to `false` again and restart your game, as you don't want it to continue removing things automatically.

In theory that should delete the TNT and allow you to use your world again, although it might not, since it's being caused by an inventory pet... but it's worth a shot.
I hope this helps, I know how frustrating things like that can be!

**Comment by TigerWalts** [comment] 2018-08-09 22:19
I've seen this happen twice.

The Chance Cube must be spawning an ocelot with a primed TNT riding it. The Inventory Pets mod assumes all entity passengers inherit the `EntityLiving` class and so the exception occurs.

Resolved in both cases by opening the region file in NBTExplorer and deleting the contents of the `passengers` node for the ocelot entity. You could also just delete the ocelot entity, but it was recently international cat day... so no.

---

It appears to be a reward built into Chance Cubes: `config\ChanceCubes\chancecubes.cfg`

```
    #  [default: true]
    B:"chancecubes:TNT_Bats"=true

    #  [default: true]
    B:"chancecubes:TNT_Cat"=true
```

There's also one for bats it seems.

**Comment by scalda** [comment] 2018-08-12 10:28
thanks this will be sorted in 1.5.1

**Closed as completed by scalda** 2018-08-12 10:28 UTC
Labels: Fix in the comments
