### ISSUE TITLE
Extra Utilities Book

### ISSUE THREAD

**Issue by VerneGeer** [scalda/Foolcraft_3#223] opened 2018-07-19 10:13 UTC
## Issue Description
When using extra utilities i cant open guide book. Crash the game.

## Reproduce Steps
Try opening book -> crashes

**Comment by galsol** [comment] 2018-07-21 17:47
Can confirm I am having this issue as well.
I tried launching an instance with only Extra Utilities 2 (same version as pack) and the same FML version,
and not crash while opening the book.

**Comment by Mrbysco** [comment] 2018-07-21 19:02
Log please

**Comment by galsol** [comment] 2018-07-21 19:16
Would my crash report and log help?

**Comment by Mrbysco** [comment] 2018-07-21 20:48
Yes

**Comment by galsol** [comment] 2018-07-22 13:15
crash report - https://pastebin.com/mYenFMvF
log - https://pastebin.com/BxftCSjL
Sorry for the delay ^^
Thanks!

**Comment by ScottDWebster** [comment] 2018-07-31 21:32
I get the same result when attempting to open the book.

**Comment by Mrbysco** [comment] 2018-08-01 23:25
Duplicate of https://github.com/scalda/Foolcraft_3/issues/146

**Comment by scalda** [comment] 2018-08-12 11:49
been reported her https://github.com/rwtema/extrautilities_old_issues/issues/1786

**Closed as completed by scalda** 2018-08-12 11:49 UTC
Labels: duplicate
