### ISSUE TITLE
Server crash when using emc condensers

### ISSUE THREAD

**Issue by Ju1c3y** [scalda/Foolcraft_3#206] opened 2018-07-16 01:47 UTC
## Issue Description
I have discovered a hard crash bug that causes a server to crash instantly, along with the client if repeated in singleplayer. I have not altered the pack in any way, including leaving the config files to the defaulted values. Whenever an item is piped into an equivalent energistics "Emc Condenser", the server that I am running crashes instantly. in order to fix this with a server, it is required that the world be loaded in McEdit, and the condenser be removed through the program, or the server will not start. When run on my server, It does not produce any sort of crash log, but below is a crash log from a client, using the import method of a hopper.

## Reproduce Steps
The crash can be produced by simply attaching an emc condenser to a functional ME system, and attempting to pipe items in (through all methods, as far as I can tell.) any side. the result is an instant client crash when done in singleplayer, or server crash when in multiplayer. I have tested with several tiers of condenser, and have had emc storage cells in the system every time.
https://pastebin.com/kPCjs411

**Comment by nzminecraftDOTcom** [comment] 2018-07-16 10:24
Are you using any upgrades in the export bus when pumping into the condenser, I had a crash loop of my server a few hours ago where someone had done what you had described but with an upgrade of some form in the export bus.
Condenser MkI or MkII?
I had no issues with this in 1.4.5 while i was running it, however my modpack was heavily modified.

**Comment by Mrbysco** [comment] 2018-07-16 12:49
This is an issue with Equivalent Enegistics.

**Comment by Ju1c3y** [comment] 2018-07-16 16:25
> Are you using any upgrades in the export bus when pumping into the condenser

No upgrades, but originally was using thermal dynamics to move items in.
> Condenser MkI or MkII

Emc condensers from Equivalent Energistics, not Project E condensers.
> This is an issue with Equivalent Energistics.

Is there a fix coming soon or a way i can modify the pack apart from getting an older version of Equivalent Energistics?

**Comment by scalda** [comment] 2018-07-18 12:46
I believe this is because AE2 is a lot newer in the pack then what EE is using and this is causing the crash we are all seeing.

**Comment by xGarionx** [comment] 2018-07-22 05:49
It is exactly the problem . The EE version uses a method call on AE2 when the attempt to generate EMC starts (no matter the item pumped in and no matter the emc condeners from EE and no matter the way the item is pumpend in) ,becouse AE2 changed the data type required for the hard coded function the EE implementation calls on basicly nothing. Since its a ticking entitiy that constantly attemps the import any server/java vm crashes due to bad safety measurement and bad error handling implementation.

I suggest to change the recipe for the Condenser (ProjectE) and remove Equivalent Exchange until its fixed

**Comment by scalda** [comment] 2018-08-12 12:42
update to Beta 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed beforehand

**Comment by aMannus** [comment] 2018-08-15 19:34
I can confirm 1.5 Beta only makes this problem worse, in a way. In 1.4.5 the game only crashes when you try to pump items into a condenser, in 1.5 the game crashes as soon as you put in an EMC disk into an ME system. 

ProjectE needs to be downgraded to 1.3.1 to fix the problem in FC3 1.4.5, instead of 1.3.1b. This is explicitly stated on the Equivalent Energistics curseforge as well, by the way..

For more info on this matter: https://github.com/Mordenkainen/EquivalentEnergistics/issues/98

EDIT: This issue was also already linked in the other issue that this is considered a duplicate of.

**Comment by xGarionx** [comment] 2018-08-15 19:46
I can confirm the issue stated by aMannus aswell (wasnt able to post it earlier) , there is an immediate crash caused by ticking entity.

**Closed as completed** 2018-08-20 10:00 UTC
Labels: bug, duplicate, Please report to relevant Mod Author, update to Beat 1.5 and test please, Close in 7 days

**Comment by aMannus** [comment] 2018-08-20 10:04
So was this closed because there is a fix or what's the reason exactly?

**Comment by scalda** [comment] 2018-08-20 10:17
i have downgraded Project e for 1.5.1 version of the pack

**Comment by aMannus** [comment] 2018-08-20 10:18
Sweet, thank you for the clarification. I will test this as soon as I have grabbed the 1.5.1 version.

**Comment by scalda** [comment] 2018-08-20 10:20
I am still working on the list of fixes at the moment but my time has been consumed with this project at the moment https://www.gofundme.com/the-carastudio
