### ISSUE TITLE
[ModSuggestion] Extra Cells

### ISSUE THREAD

**Issue by TimTheMcNugget** [scalda/Foolcraft_3#187] opened 2018-07-09 14:22 UTC
I really want to be able to store fluids in my AE2 system. This is something you are only able to do with Refined Storage right now and it would be really awsome to also be able to do it with AE2.

**Comment by Mrbysco** [comment] 2018-07-09 16:05
Duplicate of #128

**Comment by Mrbysco** [comment] 2018-07-09 16:05
Also no template is used.

**Closed** 2018-07-09 17:36 UTC
Labels: duplicate
