### ISSUE TITLE
Mob Grinders cause crash if allowed to kill enemies for extended times. Also weird behavior Version 1.4.5 @mob_grinding_utils

### ISSUE THREAD

**Issue by Kakiharu** [scalda/Foolcraft_3#219] opened 2018-07-18 03:31 UTC
## Issue Description
Mob Grinders cause crash if allowed to kill enemies for extended times. Enemies are Resturbed Wither skeletons from Rouge Dungeon at max speed upgrades. Also when you turn on a grinder using a lever and turn it off again, it proceeds to spaz out and not look the same as when first placed stationary. 

## Reproduce Steps
Throw lots of enemies at multiple grinders. Also try turning on off with lever to see strange reactions.

**Comment by Revvilo** [comment] 2018-07-18 07:48
Do you mean the Mob Masher? Cause I've also had it crash me with the same spawner setup.
I'm pretty sure the crash is caused by the Repellant enchantment from EnderIO that was added in 1.4.5, which has a chance to teleport the attacker randomly upon being damaged.

This is the crash I get;
```
java.lang.NullPointerException: Ticking block entity
	at crazypants.enderio.base.teleport.RandomTeleportUtil.doTeleport(RandomTeleportUtil.java:134)
	at crazypants.enderio.base.teleport.RandomTeleportUtil.doTeleport(RandomTeleportUtil.java:94)
	at crazypants.enderio.base.teleport.RandomTeleportUtil.teleportEntity(RandomTeleportUtil.java:63)
	at crazypants.enderio.base.enchantment.EnchantmentRepellent.func_151367_b(EnchantmentRepellent.java:55)
	at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:465)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:124)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:168)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1401)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1420)
	at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:95)
	at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:59)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

I tested it by summoning a zombie that can pick up loot and giving him a chestplate with `Repellant IV` on it, then throwing him into a Masher... crashes straight away.

The spazzing/vibrating seems to just be a weird thing with the mod and the way the dev has attempted to make them stop in place (rather than resetting to their normal position) when they lose redstone signal - similar to the way the vanilla spawner's spinning mob used to vibrate when out of range of a player.

I miss having the looting and beheading of the Masher for my resturbed spawners...

**Comment by scalda** [comment] 2018-07-18 12:11
this is due to the new ender io enchant not working with fake players they have fixed it in their code I am awaiting an update of the mod so i can push a foolcraft update

**Comment by Kakiharu** [comment] 2018-07-18 18:52
Yea, thats what I meant. Thats my exact issue. Was running my power off of bones, but had to put that on hold. Awesome thanks for the progress update!

**Comment by scalda** [comment] 2018-08-12 11:51
Update to 1.5 beta this is now fixed

**Closed as completed by scalda** 2018-08-12 11:51 UTC
Labels: duplicate, invalid, Please report to relevant Mod Author, update to Beat 1.5 and test please
