### ISSUE TITLE
Ghast Statue not Dropping

### ISSUE THREAD

**Issue by KyanG7** [scalda/Foolcraft_3#138] opened 2018-06-13 06:18 UTC
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [ ] In single player
     - [x ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
After killing well over 500 ghasts, no statue had dropped for the energy condenser.

## Reproduce Steps
Kill a ton of Ghasts.

**Comment by kpeckett** [comment] 2018-06-13 07:20
Were these player kills or machine kills?

**Comment by jeviuss** [comment] 2018-06-13 10:32
It's confirmed bugged on reddit, as far as I'm aware they'll have it fixed next update.

**Comment by Yadokingu** [comment] 2018-06-15 00:20
Since it's required in all recipes for the energy condenser, that's still not great. That makes it uncraftable.
I don't think it's great how many statues are required in general for it, but not even being able to get the statue is of course worse.

**Comment by Protius7331** [comment] 2018-06-17 11:01
I am also having this issue, have spent a couple hours killing ghasts, first in the Nether, then in an IF Mob Duplicator, all killed with my Looting III sword. I have several stacks of ghast tears but not a single statue. With this being added to the Angel Ring recipe in the most recent update, I am still unable to craft it.

**Comment by Mrbysco** [comment] 2018-06-17 12:54
Tool effects has no effect on the dropping of statues.
The dropping of the ghast statue is fixed in a next version. So we just have to wait for Scalda to release that update

**Comment by Ferdy2003** [comment] 2018-06-27 18:14
Is this bug still in the game or was it fixed with version 1.3.1?

**Comment by KelleyEngineering** [comment] 2018-07-01 17:28
In the Meantime, create a file called "09-Ghast)loot.zs" in the scripts folder. Type the following into it. This will add the statue to the loot table (rare drop) until the update is pushed. 

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Conditions;
import loottweaker.vanilla.loot.Functions;

val ghast = LootTables.getTable("minecraft:entities/ghast");
val main = ghast.getPool("main");

main.addItemEntryHelper(<minecraft:ghast_tear>, 20, 1, [Functions.setCount(1, 2)], []);
main.addItemEntryHelper(<minecraft:gunpowder>, 30, 1, [Functions.setCount(1, 2)], []);
main.addItemEntryHelper(<statues:blockghaststatue>, 2, 1, [], [Conditions.killedByPlayer()]);

**Comment by Mrbysco** [comment] 2018-07-01 18:00
I have one issue with that "fix". 
There's a reason statues aren't added to any loottables. and that is to stop minecraft enchantments from affecting the drop rate.

By adding it to the loot table it would drop yes. But effects like looting would make it drop multiple which it should never do.

**Comment by scalda** [comment] 2018-07-01 18:02
@KelleyEngineering 1.4.2 is being released tomorrow with beta status

**Comment by KelleyEngineering** [comment] 2018-07-01 18:03
Would you prefer I remove it?

**Comment by Mrbysco** [comment] 2018-07-01 18:08
I was just stating that it would make getting statues too easy. Do whatever you like. I'm really sorry for making them not drop before. Was totally my fault as I missed a line in code

**Comment by KelleyEngineering** [comment] 2018-07-01 18:10
S'all good. I just wanted a temporary solution for the fans.

**Comment by scalda** [comment] 2018-07-01 18:18
link to 1.4.2 if you want to test it out @KelleyEngineering [1.4.2](https://cdn.discordapp.com/attachments/428546411257266176/463041484770377738/Foolcraft_3-Beta-1.4.2.zip)

**Comment by SirioIlBe** [comment] 2018-07-03 11:37
so when is 1.4.2 released? you said it will be released tomorrow (but it was 2 days ago). i don't know what to do with this download that you put up here >.<

**Comment by Mrbysco** [comment] 2018-07-06 15:12
1.4.4 has been released

**Closed by Mrbysco** 2018-07-06 15:13 UTC
