### ISSUE TITLE
[Suggested Mod] Bibliocraft

### ISSUE THREAD

**Issue by BertTF2** [scalda/Foolcraft_3#216] opened 2018-07-17 15:59 UTC
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
Bibliocraft's furniture is much better looking than Mr Crayfish's mod in my opinion, and it has some functional furniture like typewriters, printing presses, and dinner plates that Mr Crayfish's mod lacks
Bibliocraft link: https://www.bibliocraftmod.com/

**Comment by Mrbysco** [comment] 2018-07-17 16:18
Bibliocraft has been suggested already but was denied.

Duplicate of https://github.com/scalda/Foolcraft_3/issues/107

**Closed as completed** 2018-07-18 12:13 UTC
